#  ====================================================================================================   
#                                                                                                         
#    SuPReMo: Surrogate Parameterised Respiratory Motion Model                                            
#             An implementation of the generalised motion modelling and image registration framework      
#                                                                                                         
#    Copyright (c) University College London (UCL). All rights reserved.                                  
#                                                                                                         
#    This software is distributed WITHOUT ANY WARRANTY; without even                                      
#    the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR                                  
#    PURPOSE.                                                                                             
#                                                                                                         
#    See LICENSE.txt in the top level directory for details.                                              
#                                                                                                         
#  ====================================================================================================   


# Most light-weight
dist: trusty

# Allow spin up of container instead of asking for full VM
sudo: false

language: cpp

before_script:
  # Export variables used during building and testing
  - export src_dir=`pwd`
  - export build_dir="${src_dir}/build"
  - export dep_dir="${build_dir}/dependencies"
  - export niftyreg_source_dir="${dep_dir}/niftyreg_source"
  - export niftyreg_install_dir="${dep_dir}/niftyReg_install"
  - export niftyreg_build_dir="${dep_dir}/niftyReg_build"
  - export supremo_build_dir="${build_dir}/supremo_build"
  - export supremo_install_dir="${build_dir}/supremo_install"
  # Printing build information
  - echo "Building SuPReMo"
  - echo "source_dir           - ${src_dir}"
  - echo "Dependencies"
  - echo "============"
  - echo "build_dir           - ${build_dir}"
  - echo "dep_dir              - ${dep_dir}"
  - echo "niftyreg source dir  - ${niftyreg_source_dir}"
  - echo "niftyreg build dir   - ${niftyreg_build_dir}"
  - echo "niftyreg install dir - ${niftyreg_install_dir}"
  - echo "supremo"
  - echo "========="
  - echo "supremo build dir    - ${supremo_build_dir}"
  - echo "supremo install dir  - ${supremo_install_dir}"

script:
  # Get the version information
  - echo `cmake --version`

  # Build nifty reg dependency
  - echo "Building dependency > niftyreg"
  - echo "=============================="
  - mkdir -p ${dep_dir}
  - cd ${dep_dir}
  - git clone https://github.com/KCL-BMEIS/niftyreg.git ${niftyreg_source_dir}
  - mkdir -p ${niftyreg_build_dir}
  - mkdir -p ${niftyreg_install_dir}
  - cd ${niftyreg_build_dir}
  # Configure cmake for nifty reg
  - cmake 
      -DBUILD_ALL_DEP:BOOL=ON 
      -DCMAKE_CONFIGURATION_TYPES:STRING=Release 
      -DCMAKE_INSTALL_PREFIX:STRING=${niftyreg_install_dir} 
      ${niftyreg_source_dir}
  - cmake --build . -- -j2
  - cmake --install
  # Build SuPReMo
  - echo "Building > SuPReMo"
  - echo "===================="
  - mkdir -p ${supremo_build_dir}
  - mkdir -p ${supremo_install_dir}
  - cd ${supremo_build_dir}
  # Configure SuPReMo with the required niftyreg dependency
  - cmake 
        -DNiftyReg_DIR:STRING=${niftyreg_install_dir} 
        -DCMAKE_CONFIGURATION_TYPES:STRING=Release 
        -DCMAKE_INSTALL_PREFIX:STRING=${supremo_install_dir} 
        -DBUILD_TESTING:BOOL=ON
        ${src_dir}
  - cmake --build . -- -j2
  - cmake --install





