name: Build
on:
  push:
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dependency nifty-reg
        uses: actions/checkout@v4.1.1
        with:
            repository: KCL-BMEIS/niftyreg
            path: $GITHUB_WORKSPACE/niftyregSource

      - name: Configure Project
        uses: threeal/cmake-action@v1.3.0
        with:
            run-build: true
            run-test: false
            options:  "CMAKE_INSTALL_PREFIX=$GITHUB_WORKSPCE/niftyRegInstall"
            source-dir: niftyregSource
            build-dir: niftyregBuild

      - name: Install nifty-reg dependency 
        run: |
              cd ${GITHUB_WORKSPACE}/niftyregSource
              pwd
              ls -la
              make install

      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
            path: SuPReMoSource

#      - name: Build Project
#        runs: cmake --build build##
#
#      - name: Test Project
#        runs: ctest --test-dir build